### ISSUE TITLE
Use only Dumper::dump()

### ISSUE THREAD

**Issue by jirimatejka1** [kutny/tracy-bundle#6]
Hello,
is it possible to use only formated dump output? I am trying to find some way to disable "red debugger screen" and use symfony debug bar, but I really like dump output from Nette.
Thanks a lof for answer
Jiri

**Comment by kutny** [comment]
Hi, I guess that you don't need this bundle. Just require tracy/tracy in your composer.json file and all Tracy libraries should be autoloaded to Symfony2.

**Comment by jirimatejka1** [comment]
Hi, thank you for your quick answer, I really appriciate it.
Jiri
